<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="MateriasCursandoDeAlumnoService"
     targetNamespace="http://oracle.com/sca/soapservice/SistemaDeInscripsiones/sistemaInscripsiones/MateriasCursandoDeAlumnoService"
     xmlns:inp2="http://www.proyectoInscripcion.org"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:inp1="http://oracle.com/sca/soapservice/SistemaDeInscripsiones/sistemaInscripsiones/MateriasCursandoDeAlumnoService"
     xmlns:tns="http://oracle.com/sca/soapservice/SistemaDeInscripsiones/sistemaInscripsiones/MateriasCursandoDeAlumnoService"
    >
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://oracle.com/sca/soapservice/SistemaDeInscripsiones/sistemaInscripsiones/MateriasCursandoDeAlumnoService"
             elementFormDefault="qualified">
            <element name="string" type="string"/>
        </schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.proyectoInscripcion.org" schemaLocation="xsd/esquema.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="part1" element="inp1:string"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="part1" element="inp2:materias"/>
    </wsdl:message>
    <wsdl:portType name="MateriasCursandoDeAlumno_ptt">
        <wsdl:operation name="MateriasCursandoDeAlumno">
            <wsdl:input message="inp1:requestMessage"/>
            <wsdl:output message="inp1:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
