<?binding.jca NuevoAlumnoParaIncribir_db.jca?>
<wsdl:definitions name="NuevoAlumnoParaIncribir" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SistemaDeInscripsiones/sistemaInscripsiones/NuevoAlumnoParaIncribir" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SistemaDeInscripsiones/sistemaInscripsiones/NuevoAlumnoParaIncribir" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/NuevoAlumnoParaIncribir">
    <plt:partnerLinkType name="NuevoAlumnoParaIncribir_plt">
        <plt:role name="NuevoAlumnoParaIncribir_role">
            <plt:portType name="tns:NuevoAlumnoParaIncribir_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/NuevoAlumnoParaIncribir" schemaLocation="xsd/NuevoAlumnoParaIncribir_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="InscriptosCollection_msg">
        <wsdl:part name="InscriptosCollection" element="top:InscriptosCollection"/>
    </wsdl:message>
    <wsdl:portType name="NuevoAlumnoParaIncribir_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:InscriptosCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
