<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../Mediator1.wsdl"/>
      <rootElement name="AlumnosCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/iniciar"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../iniciar.wsdl"/>
      <rootElement name="AlumnosCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/iniciar"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.6.0(build 111214.0600.1553) AT [TUE MAR 10 11:30:16 ART 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/SistemaDeInscripsiones/DarDeBajaMAteria/iniciar"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:inp1="http://xmlns.oracle.com/pcbpel/adapter/db/top/iniciar"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:tns="http://xmlns.oracle.com/SistemaDeInscripsiones/DarDeBajaMAteria/Mediator1"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl inp1 xsd wsdl tns ns0 plt xp20 bpws bpel mhdr oraext dvm hwf med ids bpm xdk xref bpmn ora socket ldap">
  <xsl:template match="/">
    <inp1:AlumnosCollection>
      <inp1:Alumnos>
        <inp1:nroInscripcion>
          <xsl:value-of select="/inp1:AlumnosCollection/inp1:Alumnos/inp1:nroInscripcion[1]"/>
        </inp1:nroInscripcion>
        <inp1:nombre>
          <xsl:value-of select="/inp1:AlumnosCollection/inp1:Alumnos/inp1:nombre[1]"/>
        </inp1:nombre>
        <inp1:apellido>
          <xsl:value-of select="/inp1:AlumnosCollection/inp1:Alumnos/inp1:apellido[1]"/>
        </inp1:apellido>
        <inp1:edad>
          <xsl:value-of select="/inp1:AlumnosCollection/inp1:Alumnos/inp1:edad[1]"/>
        </inp1:edad>
        <inp1:dni>
          <xsl:value-of select="/inp1:AlumnosCollection/inp1:Alumnos/inp1:dni[1]"/>
        </inp1:dni>
      </inp1:Alumnos>
    </inp1:AlumnosCollection>
  </xsl:template>
</xsl:stylesheet>
