<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../BuscarTodosLosAlumnosDeLAMateria.wsdl"/>
      <rootElement name="InscriptosCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/BuscarTodosLosAlumnosDeLAMateria"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../BuscarTodosLosAlumnosDeLMateriaService.wsdl"/>
      <rootElement name="InscriptosCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/BuscarTodosLosAlumnosDeLAMateria"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.6.0(build 111214.0600.1553) AT [TUE MAR 10 10:39:16 ART 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:inp1="http://xmlns.oracle.com/singleString"
                xmlns:ns0="http://oracle.com/sca/soapservice/SistemaDeInscripsiones/DarDeBajaMAteria/BuscarTodosLosAlumnosDeLMateriaService"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/BuscarTodosLosAlumnosDeLAMateria"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SistemaDeInscripsiones/DarDeBajaMAteria/BuscarTodosLosAlumnosDeLAMateria"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:bpmn="http://schemas.oracle.com/bpm/xpath"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl plt wsdl top tns xsd inp1 ns0 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref bpmn ldap">
  <xsl:template match="/">
    <top:InscriptosCollection>
      <xsl:for-each select="/top:InscriptosCollection/top:Inscriptos">
        <top:Inscriptos>
          <top:materia>
            <xsl:if test="top:materia/@xsi:nil">
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="top:materia/@xsi:nil"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="top:materia"/>
          </top:materia>
          <top:alumno>
            <xsl:if test="top:alumno/@xsi:nil">
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="top:alumno/@xsi:nil"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="top:alumno"/>
          </top:alumno>
          <top:estado>
            <xsl:if test="top:estado/@xsi:nil">
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="top:estado/@xsi:nil"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="top:estado"/>
          </top:estado>
        </top:Inscriptos>
      </xsl:for-each>
    </top:InscriptosCollection>
  </xsl:template>
</xsl:stylesheet>
