<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="MateriasCursandoConEstadoService"
     targetNamespace="http://oracle.com/sca/soapservice/SistemaDeInscripsiones/sistemaInscripsiones/MateriasCursandoConEstadoService"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://oracle.com/sca/soapservice/SistemaDeInscripsiones/sistemaInscripsiones/MateriasCursandoConEstadoService"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <plnk:partnerLinkType name="MateriasCursandoService">
        <plnk:role name="MateriasCursandoConEstado_ptt" portType="tns:MateriasCursandoConEstado_ptt"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://oracle.com/sca/soapservice/SistemaDeInscripsiones/sistemaInscripsiones/MateriasCursandoConEstadoService"
         location="http://BUE-858029A-5.usersad.everis.int:7001/soa-infra/services/default/Project1!1.0/MateriasCursandoConEstadoService.wsdl"/>
</wsdl:definitions>
