<?binding.jca PonerCupos0_db.jca?>
<wsdl:definitions name="PonerCupos0" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SistemaDeInscripsiones/DarDeBajaMAteria/PonerCupos0" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SistemaDeInscripsiones/DarDeBajaMAteria/PonerCupos0" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/PonerCupos0">
    <plt:partnerLinkType name="PonerCupos0_plt">
        <plt:role name="PonerCupos0_role">
            <plt:portType name="tns:PonerCupos0_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/PonerCupos0" schemaLocation="xsd/PonerCupos0_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="MateriasCollection_msg">
        <wsdl:part name="MateriasCollection" element="top:MateriasCollection"/>
    </wsdl:message>
    <wsdl:portType name="PonerCupos0_ptt">
        <wsdl:operation name="update">
            <wsdl:input message="tns:MateriasCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
