<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="BPELProcess1"
     targetNamespace="http://xmlns.oracle.com/SistemaDeInscripsiones/ProjectPruebarules/BPELProcess1"
     xmlns:ns1="http://www.example.org"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:client="http://xmlns.oracle.com/SistemaDeInscripsiones/ProjectPruebarules/BPELProcess1"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="BPELProcess1">
        <plnk:role name="BPELProcess1Provider" portType="client:BPELProcess1"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://www.example.org" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
             xmlns:client="http://xmlns.oracle.com/SistemaDeInscripsiones/ProjectPruebarules/BPELProcess1"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
            <import namespace="http://www.example.org" schemaLocation="xsd/elem.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="BPELProcess1RequestMessage">
        <wsdl:part name="payload" element="ns1:numero"/>
    </wsdl:message>
    <wsdl:message name="BPELProcess1ResponseMessage">
        <wsdl:part name="payload" element="ns1:numero"/>
    </wsdl:message>
    <wsdl:portType name="BPELProcess1">
        <wsdl:operation name="process">
            <wsdl:input message="client:BPELProcess1RequestMessage"/>
            <wsdl:output message="client:BPELProcess1ResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
